version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing AWS SAM CLI..."
      - pip install aws-sam-cli
  build:
    commands:
      - echo "Building the Serverless App..."
      - sam build
  post_build:
    commands:
      - echo "Build completed successfully."
artifacts:
  type: zip
  files:
    - '**/*'
